workspace:
  base: /go
  path: src/github.com/uswitch/s3-downloader

pipeline:
  build:
    image: golang:1.9
    commands:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/s3-downloader

  publish_release:
    when:
      event: tag
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - bin/s3-downloader
